---
dependencies: []

galaxy_info:
  author: apolloclark
  description: Install and configure an Ubuntu base image, with Elastic monitoring
  license: "license (BSD, MIT)"
  min_ansible_version: 2.0
  platforms:
    - name: Ubuntu
      versions:
      - all
  galaxy_tags:
    - development
    - web
    - php
    - apache
    - mysql
    - security
    - elk
    - devsecops