# http://docs.ansible.com/ansible/latest/galaxy.html#installing-multiple-roles-from-a-file
---
- src: geerlingguy.firewall
- src: geerlingguy.git                # https://github.com/geerlingguy/ansible-role-git
- src: apolloclark.nano_highlighting  # https://github.com/apolloclark/ansible-role-nano-highlighting
- src: apolloclark.aws_cli            # https://github.com/apolloclark/ansible-role-aws-cli
- src: rvm.ruby                       # https://github.com/rvm/rvm1-ansible
- src: geerlingguy.ruby               # https://github.com/geerlingguy/ansible-role-ruby
- src: apolloclark.osquery            # https://github.com/apolloclark/ansible-role-osquery
- src: apolloclark.filebeat           # https://github.com/apolloclark/ansible-role-filebeat
- src: apolloclark.metricbeat         # https://github.com/apolloclark/ansible-role-metricbeat
- src: apolloclark.heartbeat          # https://github.com/apolloclark/ansible-role-heartbeat
- src: apolloclark.packetbeat         # https://github.com/apolloclark/ansible-role-packetbeat
- src: apolloclark.auditbeat          # https://github.com/apolloclark/ansible-role-auditbeat
