# http://docs.ansible.com/ansible/latest/playbooks_variables.html#variable-file-separation
---
hostname: all

# geerlingguy/ntp
ntp_timezone: America/New_York

# geerlingguy/firewall
firewall_allowed_tcp_ports:
  - "22"
  - "25"

# apolloclark/aws-cli
awscli:
  pip_user: 
    - root

# rvm.ruby
rvm1_user: "root"
rvm1_install_path: '/home/{{ rvm1_user }}/.rvm'
rvm1_install_flags: '--auto-dotfiles --user-install'

# geerlingguy.ruby
ruby_install_gems:
  - rspec
  - serverspec
ruby_install_gems_user: "root"



# apolloclark/osquery
osquery:
  version: "3.3.2-1.linux"

# apolloclark/filebeat
filebeat:
 version: "6.6.2"
 install_only: "true"

# apolloclark/metricbeat
metricbeat:
 version: "6.6.2"
 install_only: "true"

# apolloclark/heartbeat
heartbeat:
 version: "6.6.2"
 install_only: "true"

# apolloclark/packetbeat
packetbeat:
  version: "6.6.2"
  install_only: "true"

# apolloclark/auditbeat
auditbeat:
  version: "6.6.2"
  install_only: "true"
