# http://docs.ansible.com/ansible/latest/playbooks_best_practices.html#directory-layout
---
# playbook.yml

- hosts: all
  connection: ssh
  gather_facts: yes
  become: true
  vars_files:
    - "vars.yml"
  roles:
    - geerlingguy.firewall
    - geerlingguy.git
    - apolloclark.nano_highlighting
    - apolloclark.aws_cli
    - rvm.ruby
    - geerlingguy.ruby
    - apolloclark.osquery
    - apolloclark.filebeat
    - apolloclark.metricbeat
    - apolloclark.heartbeat
    - apolloclark.packetbeat
    - apolloclark.auditbeat
